### ISSUE TITLE
V2.4.1 not tagged in VeeningLab repo

### ISSUE THREAD

**Issue by tfmorris** [afombravo/2FAST2Q#5]
It doesn't look like there's tag associated with the latest release, making it show up on both Zenodo & Github as "untagged-xxx" instead of V2.4.1.

https://github.com/veeninglab/2FAST2Q/releases/tag/untagged-706010bf214eea38485f
https://zenodo.org/record/6565942#.Yqs8ABPMJTY

**Comment by afombravo** [comment]
Thanks. Fixed!
