### ISSUE TITLE
pair-end and single-end file

### ISSUE THREAD

**Issue by vuhongai** [afombravo/2FAST2Q#6]
Hello, thank you for sharing. It's really fast indeed.
I have 1 question: how can I specify if the fastq format is from single-end or pair-end configuration. If I have R1 and R2 files from pair-end reads, I should count it individually or there is better way to do that?
Thank you.
Ai

**Comment by afombravo** [comment]
Hi. Thank you for your coment. Currently 2fast2q doesn't support pair ended format, as this would required more advanced alignment algorithms like the ones found in bowtie2, for example. For your case, the best you can do is indeed run it twice, keeping in mind that you will probably need a filé with the reverse complement of the features you are trying to align to. If you describe your use case, and if you want, I can help you further. Cheers, Afonso

**Comment by vuhongai** [comment]
Hi, thank you for the quick reply.
In my experiment, I deep sequence a PCR product of a concatenation of 3 16-bp barcodes. The amplicon length including the PCR primer is 120 bp. I did the paired-end sequencing of those and would like to count individual variants. I think I would do as you suggested, do it separately and try to merge results of the reverse-complement sequences.
